### ISSUE TITLE
Parameter code not returned from site information

### ISSUE THREAD

**Issue by pinshuai** [USGS-python/dataretrieval#34] opened 2021-07-30 05:16 UTC
Hi, I am trying to retrieve the site information by given a huc region, but the `parm_cd` is not returned as one of the columns. I have used R-dataretrieval in the past, and it has always returned the `parm_cd` for me. I wonder if similar information could be returned using this python package.

This is what I have used in the R package:

```
df <- readNWISdata(huc = HUCcode, parameterCd = pCode, service="site", 
                     seriesCatalogOutput=TRUE)
```

The dataframe returned the following columns:
```
'agency_cd''site_no''station_nm''site_tp_cd''dec_lat_va''dec_long_va''coord_acy_cd''dec_coord_datum_cd''alt_va''alt_acy_va''alt_datum_cd''huc_cd''data_type_cd''parm_cd''stat_cd''ts_id''loc_web_ds''medium_grp_cd''parm_grp_cd''srs_id''access_cd''begin_date''end_date''count_nu'
```

This is what I used in python:
```
df = nwis.get_record(huc = HUCcode, parameterCd= pCode, service='site',
                   seriesCatalogOutput = True)
```
And this is what's returned:
```
'agency_cd', 'site_no', 'station_nm', 'site_tp_cd', 'lat_va', 'long_va',
       'dec_lat_va', 'dec_long_va', 'coord_meth_cd', 'coord_acy_cd',
       'coord_datum_cd', 'dec_coord_datum_cd', 'district_cd', 'state_cd',
       'county_cd', 'country_cd', 'land_net_ds', 'map_nm', 'map_scale_fc',
       'alt_va', 'alt_meth_cd', 'alt_acy_va', 'alt_datum_cd', 'huc_cd',
       'basin_cd', 'topo_cd', 'instruments_cd', 'construction_dt',
       'inventory_dt', 'drain_area_va', 'contrib_drain_area_va', 'tz_cd',
       'local_time_fg', 'reliability_cd', 'gw_file_cd', 'nat_aqfr_cd',
       'aqfr_cd', 'aqfr_type_cd', 'well_depth_va', 'hole_depth_va',
       'depth_src_cd', 'project_no'
```

The columns are also missing `begin_date`, `end_date`, and `count_nu`, which would be very helpful.

Any idea?

**Comment by elbeejay** [comment] 2022-12-19 22:30
There are several reasons this didn't work at the time, and I'm going to guess at some of these as your example inputs are somewhat generic. But I was able to reproduce the behavior you reported using the following code.

In R:
```
> data <- readNWISdata(huc=20, parameterCd='00060', service='site', seriesCatalogOutput=TRUE)
> colnames(data)
 [1] "agency_cd"          "site_no"            "station_nm"         "site_tp_cd"        
 [5] "dec_lat_va"         "dec_long_va"        "coord_acy_cd"       "dec_coord_datum_cd"
 [9] "alt_va"             "alt_acy_va"         "alt_datum_cd"       "huc_cd"            
[13] "data_type_cd"       "parm_cd"            "stat_cd"            "ts_id"             
[17] "loc_web_ds"         "medium_grp_cd"      "parm_grp_cd"        "srs_id"            
[21] "access_cd"          "begin_date"         "end_date"           "count_nu"          
```

and then in Python:
```
>>> data = nwis.get_record(huc='20', parameterCd='00060', service='site', seriesCatalogOutput=True)
>>> data.columns
Index(['agency_cd', 'site_no', 'station_nm', 'site_tp_cd', 'lat_va', 'long_va',
       'dec_lat_va', 'dec_long_va', 'coord_meth_cd', 'coord_acy_cd',
       'coord_datum_cd', 'dec_coord_datum_cd', 'district_cd', 'state_cd',
       'county_cd', 'country_cd', 'land_net_ds', 'map_nm', 'map_scale_fc',
       'alt_va', 'alt_meth_cd', 'alt_acy_va', 'alt_datum_cd', 'huc_cd',
       'basin_cd', 'topo_cd', 'instruments_cd', 'construction_dt',
       'inventory_dt', 'drain_area_va', 'contrib_drain_area_va', 'tz_cd',
       'local_time_fg', 'reliability_cd', 'gw_file_cd', 'nat_aqfr_cd',
       'aqfr_cd', 'aqfr_type_cd', 'well_depth_va', 'hole_depth_va',
       'depth_src_cd', 'project_no'],
      dtype='object')
```

The reason your input didn't work as you might have expected, is that passing the boolean `True` doesn't actually make it into the API query request the way `dataretrieval` is structured. So I'll be adding some additional documentation and an example of how to properly do this as I create a PR for this issue. To ensure the `seriesCatalogOutput` parameter is set as you expect, you actually need to pass a string `"True"` as a keyword argument to `get_record()`. However, even if you had done this, it won't work as the code is currently written. This is because there is a hard parameter setting to request the data in the "expanded_rdb" format ([L468](https://github.com/USGS-python/dataretrieval/blob/46eb1dd08ef96901644658a85fa88735c0c387e4/dataretrieval/nwis.py#L468)) and that format is actually incompatible with setting `seriesCatalogOutput` to True as that API query fails.

So resolving this issue is going to involve:
- Checking if `seriesCatalogOutput` is set to True before assigning expanded_rdb
- Writing some tests around this functionality
- Creating better documentation and examples on how to get the more detailed output

Running a rough demo in my local environment gets me some output with fields that match the ones you obtained with R, in particular the ones you were most interested in.

**Closed** 2022-12-20 16:48 UTC
Labels: bug, documentation
